  name: shell commands

  on: push

  jobs:
    runs-shell-commands:
        runs-on: ubuntu-latest
        steps:
          - name: echo string
            run:  echo "Hello World"
          - name: multi line string
            run: |
                 pwd
                 node -v
    runs-windows-commands:
        runs-on: windows-latest
        needs: ["runs-shell-commands"]
        steps:
          - name: Directory
            run: pwd
            shell: bash
