
  name: shell commands

  on: push

  jobs:
    runs-shell-commands:
        run-on: ubuntu-latest
        steps:
            - name: echo string
                run: echo "Hello World"
            - name: Multi line string
                run: |
                    pwd
                    node -v
                    ls -a
